name: CI - Streamlit Forecasting App

# Trigger workflow on push or PR to main branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Setup Python
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install streamlit flake8 pytest

    # Step 4: Check Python version
    - name: Check Python version
      run: python --version

    # Step 5: Lint Python code
    - name: Lint code
      run: flake8 forecasting.py EDA.py --max-line-length=120

    # Step 6: Check Python syntax
    - name: Check syntax
      run: |
        python -m py_compile forecasting.py
        python -m py_compile EDA.py

    # Step 7: Verify data files exist
    - name: Check data files
      run: |
        test -f "agriBORA_maize_prices.csv"
        test -f "agriBORA_maize_prices_weeks_46_to_51.csv"

    # Step 8: Run Streamlit app in headless mode
    - name: Run Streamlit App
      run: streamlit run forecasting.py --server.headless true
