# .github/workflows/ci.yaml
name: Streamlit App CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install streamlit pandas pytest
    
    - name: Check file structure
      run: |
        echo "Checking required files..."
        ls -la
        echo ""
        echo "Checking data files..."
        if [ -f "agriBORA_maize_prices.csv" ]; then
          echo "✓ agriBORA_maize_prices.csv exists"
        else
          echo "✗ agriBORA_maize_prices.csv missing"
          exit 1
        fi
        
        if [ -f "agriBORA_maize_prices_weeks_46_to_51.csv" ]; then
          echo "✓ agriBORA_maize_prices_weeks_46_to_51.csv exists"
        else
          echo "✗ agriBORA_maize_prices_weeks_46_to_51.csv missing"
          exit 1
        fi
        
        if [ -f "forecasting.py" ]; then
          echo "✓ forecasting.py exists"
        else
          echo "✗ forecasting.py missing"
          exit 1
        fi
    
    - name: Test Python imports
      run: |
        python -c "
        try:
            import streamlit
            import pandas as pd
            import numpy as np
            print('✓ All imports successful')
        except ImportError as e:
            print(f'Import error: {e}')
            exit(1)
        "
    
    - name: Test data loading
      run: |
        python -c "
        import pandas as pd
        import warnings
        warnings.filterwarnings('ignore')
        
        try:
            # Test loading data
            df1 = pd.read_csv('agriBORA_maize_prices.csv')
            df2 = pd.read_csv('agriBORA_maize_prices_weeks_46_to_51.csv')
            
            print('✓ Data files loaded successfully')
            print(f'  agriBORA_maize_prices.csv: {df1.shape[0]} rows, {df1.shape[1]} columns')
            print(f'  agriBORA_maize_prices_weeks_46_to_51.csv: {df2.shape[0]} rows, {df2.shape[1]} columns')
            
            # Check required columns
            required_cols = ['Date', 'County', 'WholeSale']
            for col in required_cols:
                if col not in df1.columns:
                    print(f'✗ Missing column in agriBORA_maize_prices.csv: {col}')
                    exit(1)
                if col not in df2.columns:
                    print(f'✗ Missing column in agriBORA_maize_prices_weeks_46_to_51.csv: {col}')
                    exit(1)
            
            print('✓ All required columns present')
            
        except Exception as e:
            print(f'✗ Error loading data: {e}')
            exit(1)
        "
    
    - name: Test forecasting.py syntax
      run: |
        python -m py_compile forecasting.py
        echo "✓ forecasting.py syntax is valid"

  deploy-check:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Deployment readiness check
      run: |
        echo "## Deployment Checklist" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "✅ All tests passed" >> $GITHUB_STEP_SUMMARY
        echo "✅ Data files verified" >> $GITHUB_STEP_SUMMARY
        echo "✅ Python dependencies installed" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Ready for deployment to Streamlit Cloud!**" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "To deploy manually:" >> $GITHUB_STEP_SUMMARY
        echo "1. Go to [Streamlit Cloud](https://share.streamlit.io/)" >> $GITHUB_STEP_SUMMARY
        echo "2. Connect your GitHub repository" >> $GITHUB_STEP_SUMMARY
        echo "3. Set main file to `forecasting.py`" >> $GITHUB_STEP_SUMMARY
